---
title: "Incarceration Trends in the United States"
author: "Sean Kim"
date: '2022-11-21'
output: html_document
---

```{r echo=FALSE, eval=TRUE, message=FALSE}
source("../source/a4-helpers.R")
source("../source/analysis.R")
```

## Abstract 
One of the sharpest manifestations of racism in the United States is its prison system. To explore deeply into this, this research will use data analysis and visualization skills to expose patterns of inequality by using the incarceration data collected by the Vera Institute.

## Introduction 
The incarceration trends in the United States exposes patterns of inequality. To show these patterns of inequality, I will do a research with data analysis and visualization skills on the incarceration data collected by the Vera Institute. One simple inequality the data show is that black people are much more likely to go to jail compared to white people.

The direct stakeholders that are impacted by this research are the people in the United States who are incarcerated. The indirect stakeholders could be people who work in the system. People who are affected by the incarcerated people such as their families could also be indirect stakeholders. The central values that I need to engage are equality and equity.

The questions that could be answered in this report are how the jail population changed over time and how it varies among states. Whether the incarceration trend differs according to the race or not could also be answered.

## Data Summary 


## Growth of the U.S. Prison Population


## Growth of Prison Population by State


## <variable comparison that reveals potential patterns of inequality>


## <a map shows potential patterns of inequality that vary geographically>
